CREATE DATABASE QLRAPCHIEUPHIM
GO
USE QLRAPCHIEUPHIM
GO
CREATE TABLE THELOAI(
	MATL VARCHAR(5) PRIMARY KEY,
	TENTL NVARCHAR(50)
);

CREATE TABLE PHIM(
	MAPHIM VARCHAR(5) PRIMARY KEY,
	TENPHIM NVARCHAR(100), 
	SOLANCHIEU INT,
	MATL VARCHAR(5),
	FOREIGN KEY (MATL) REFERENCES THELOAI(MATL)
);

CREATE TABLE RAP(
	MARAP VARCHAR(5) PRIMARY KEY,
	TENRAP NVARCHAR(100),
	DIACHI NVARCHAR(100)
);

CREATE  TABLE LICHCHIEU (
	MAXC VARCHAR(5) PRIMARY KEY,
	MARAP VARCHAR(5),
	MAPHIM VARCHAR(5),
	NGAYCHIEU DATE,
	SOLUONGVE INT CHECK (SOLUONGVE >0),
	GIAVE INT,
	CONSTRAINT FK_LC_RAP FOREIGN KEY (MARAP) REFERENCES RAP(MARAP),
	CONSTRAINT FK_LC_PHIM FOREIGN KEY (MAPHIM) REFERENCES PHIM(MAPHIM)
);

INSERT INTO THELOAI VALUES
 ('TL1', N'Hành Động'),
 ('TL2', N'Chiến Tranh'),
 ('TL3', N'Tình cảm - Hài');
 GO

 INSERT INTO PHIM VALUES
 ('P01', N'Mai',NULL,'TL3'),
 ('P02', N'Lật Mặt 7',NULL,'TL1'),
 ('P03', N'Giải Phóng Sài Gòn',NULL,'TL2'),
 ('P04', N'Thiên Mệnh Anh Hùng',NULL,'TL1'),
 ('P05', N'Biệt Đọng Sài Gon',NULL,'TL2');
 GO

INSERT INTO RAP VALUES
('R01', N'MEGA GS','Lý Chính Thắng'),
('R02', N'CGV Cinema','Điện Biên Phủ'),
('R03', N'Galaxy','NGuyễn Du'),
('R04', N'Lotte','Nam Sài Gòn');
GO
INSERT INTO LICHCHIEU VALUES 
('XC01','R02','P01','2023/02/14','300','160000'),
('XC02','R03','P01','2024/04/01','220','120000'),
('XC03','R04','P02', '2024/03/08','350','170000'),
('XC04','R03','P02', '2024/04/30','200','180000'),
('XC05','R01','P03', '2023/04/29','160','140000'),
('XC06','R03','P03', '2023/05/19','100','110000'),
('XC07','R01','P05', '2024/04/30','90','120000');
---cÂU 1:
CREATE VIEW V1 AS
SELECT
	PHIM.MAPHIM,
	PHIM.TENPHIM,
	COUNT(LICHCHIEU.MAXC) AS SOLANCHIEU
FROM PHIM
LEFT JOIN LICHCHIEU ON PHIM.MAPHIM = LICHCHIEU.MAPHIM
GROUP BY PHIM.MAPHIM, PHIM.TENPHIM;

SELECT * FROM V1
---cÂU 2:
CREATE FUNCTION F1(@MAPHIM CHAR(5))
RETURNS BIGINT
AS
BEGIN
	DECLARE @DOANHTHU BIGINT;
	IF(@MAPHIM IS NULL)
	RETURN 0;
	SELECT @DOANHTHU = SUM(SOLUONGVE * GIAVE)
	FROM LICHCHIEU
	WHERE MAPHIM = @MAPHIM;
	RETURN @DOANHTHU
END;
PRINT N'DOANH THU PHIM = ' + STR(DBO.F1(NULL),3);
PRINT N'DOANH THU PHIM = ' + STR(DBO.F1('P03'),10);
--- CÂU 3:
CREATE PROC P1 (@MAPHIM VARCHAR(5) = NULL)
AS 
BEGIN
	IF @MAPHIM IS NULL
	BEGIN 
		SELECT P.MAPHIM,
		P.TENPHIM,
		DBO.F1(P.MAPHIM) AS TONGDT
		FROM PHIM P
	END
	ELSE 
	BEGIN
	SELECT P.MAPHIM,
	P.TENPHIM,
	DBO.F1(P.MAPHIM) AS TONGDT
	FROM PHIM P
	WHERE P.MAPHIM = @MAPHIM;
	END
END.3


EXEC P1 NULL;
EXEC P1 'P02';
--- CÂU 4:
CREATE FUNCTION F2 (@THANG INT, @NAM INT)
RETURNS TABLE
AS
RETURN (
	SELECT MARAP, MAPHIM,NGAYCHIEU,SOLUONGVE
	FROM LICHCHIEU
	WHERE MONTH(NGAYCHIEU) = @THANG
	AND YEAR(NGAYCHIEU) = @NAM
);
SELECT * FROM DBO.F2(4,2024)
--- CÂU 5:
CREATE TRIGGER T1 ON LICHCHIEU
AFTER INSERT, DELETE, UPDATE
AS
BEGIN
	UPDATE PHIM
	SET SOLANCHIEU = (
	SELECT COUNT(*)
	FROM LICHCHIEU
	WHERE LICHCHIEU.MAPHIM = PHIM.MAPHIM
	);
END
--XEM LẠI BẢNG LICHCHIEU TRƯỚC KHI TEST
SELECT MAPHIM, TENPHIM,SOLANCHIEU
FROM PHIM
WHERE MAPHIM = 'P01'
--TEST LẦN 1 SOLANCHIEU TĂNG LÊN 1
INSERT INTO LICHCHIEU VALUES ('XC99','R01','P01','2024-05-10',150,100000)
--TEST LẦN 2 SOLANCHIEU GIẢM XUỐNG 1
DELETE FROM LICHCHIEU
WHERE MAXC = 'XC99'
---TEST LẦN 3ĐỔI PHIM TRONG LỊCH CHIẾU
UPDATE LICHCHIEU
SET MAPHIM= 'P02'
WHERE MAPHIM IN ('P01','P02');
----TEST LẦN 4 XEM TÔNG QUÁT
SELECT MAPHIM,TENPHIM,SOLANCHIEU
FROM PHIM

GPT
